export const flatListDatata = [
    {
        id:1,
        name:"Classes",
        icon:{
            name:"cube",
            category:"Ionicons",
            size:45
        },
        nav:"Classes"
   },
    {
        id:2,
        name:"TimeTable",
        icon:{
            name:"linechart",
            category:"AntDesign",
            size:45
        },
        nav:"TimeTable"
   },
    {
        id:3,
        name:"Profile",
        icon:{
            name:"user",
            category:"AntDesign",
            size:45
        },
        nav:"Profile"
   },
    {
        id:4,
        name:"History",
        icon:{
            name:"dashboard",
            category:"AntDesign",
            size:45
        },
        nav:"History"
   },
]